### ISSUE TITLE
How to ignore FormData?

### ISSUE THREAD

**Issue by DianaLaa** [wheresrhys/fetch-mock-jest#55]
I have a fetch method in our production code that creates `new FormData()`
I suspect this is the reason I keep getting `Unmatched POST to [url]` error.
How do I ignore the body? I've tried `matchPartialBody: true` in the options, but that does not work.

**Comment by wheresrhys** [comment]
Sorry, this is not enough information to understadn the issue. Please reopen with more information if still needed
