### ISSUE TITLE
How to configurate your library for typescript tests? (ts7016)

### ISSUE THREAD

**Issue by viT-1** [wheresrhys/fetch-mock-jest#6]
I am [using ts-jest](https://github.com/viT-1/systemjs-ts-es6-vue/blob/dd6b0b17304d5bb7ec5fea1a3acfba597efeec3a/src/jest.config.js#L61) & want to mock fetch responses (for browser code).

First of all, after installing fetch-mock-jest, in [jest setup file](https://github.com/viT-1/systemjs-ts-es6-vue/blob/dd6b0b17304d5bb7ec5fea1a3acfba597efeec3a/jest.setup.hook.js) I should write
`global.fetchMock = require('fetch-mock-jest');`
is it right or it should be `global.fetch = require('fetch-mock-jest').sandbox();`?

In ts tests I can't write global.fetchMock or fetchMock without [global declaring](https://github.com/Microsoft/TypeScript/issues/18237)
or default importing `import fetchMock from 'fetch-mock-jest';`
But if I am doing such things, why I need to make changes in jest setup script?

```
Moreover, If I import fetchMock in test, eslint show me suggestion:
Could not find a declaration file for module 'fetch-mock-jest'. ... implicitly has an 'any' type
Try `npm install @types/fetch-mock-jest` if it exists or add a new declaration (.d.ts) file containing `declare module 'fetch-mock-jest'; (ts7016)
```

Can you provide d.ts file for using typed fetchMock methods?

**Comment by viT-1** [comment]
https://github.com/wheresrhys/fetch-mock/issues/158

**Comment by viT-1** [comment]
somemodule.spec.ts
```
import fetchMock from 'fetch-mock-jest';

fetchMock.mock({
	url: 'begin:/activity/findpoints',
	response: Promise.resolve([
		{ label: 'foo' },
		{ label: 'bar' },
		{ label: 'baz' },
	]),
});
```

and typings/fetch-mock-jest.ts
`declare module 'fetch-mock-jest';`

I have an error:
```
Test suite failed to run
Jest encountered an unexpected token
This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.
...
node_modules\fetch-mock\esm\client.mjs:3552
    export default client;
    ^^^^

    SyntaxError: Unexpected token export

      at ScriptTransformer._transformAndBuildScript (../node_modules/@jest/transform/build/ScriptTransformer.js:537:17)
      at ScriptTransformer.transform (../node_modules/@jest/transform/build/ScriptTransformer.js:579:25)
      at Object.<anonymous> (../node_modules/fetch-mock-jest/fetch-mock-jest.js:4:19)
```

**Comment by wheresrhys** [comment]
Please try v1.2.0 of this library and reopen the issue if it's still broken
